# Generated by Django 5.1.6 on 2025-02-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
